### PR TITLE
Sensor name filtering

### PR DESCRIPTION
**Pull request by oxplot**
Adds a new config option `sensor_name_filter` which is a regular expression. This is useful for when different types of sensors present different metrics under the same metric name.

### CODE REVIEW

**Comment by hikhvar** [comment]
I think this is a valid use case. However, this PR might not solve the problem. Given a mqtt metric `state`. Two types of sensors (a, b) use this name to represent different logical metrics `state_a` and `state_b`. With your implementation we can either filter for either a or b. The other state will be dropped. Is this intended?

**Comment by oxplot** [comment]
> Is this intended?

No. And I see — the shape of the config file threw me off. I missed that a map is constructed to based on MQTT name.

I think the ingestor should iterate over all the rules and apply the first matching one.

**Comment by oxplot** [comment]
Done

**Comment by hikhvar** [comment]
LGTM. Thank you!

**Pull request merged**
