### PR TITLE
Docker compose & build_image

### PR DESCRIPTION
**Pull request by rgstephens**

### CODE REVIEW

**Comment by rgstephens** [comment]
Mean't to push this to my fork and test. Closing here.

**Comment by hikhvar** [comment]
Hey, quick question: What do you use your fork for? Just to get an impression what users use this code for.
I saw you build ARM docker images. This is on my todo list once goreleaser support multiarch images.

**Comment by rgstephens** [comment]
Yes, I setup this github action workflow, [build_image.yml](https://github.com/rgstephens/mqtt2prometheus/blob/master/.github/workflows/build_image.yml), to build multi-arch images of your project and push to my [docker hub repo](https://hub.docker.com/repository/docker/stephens/mqtt2prometheus). 126 downloads in a couple of weeks!

**Comment by hikhvar** [comment]
Please have look at #38 .
The next release will include multiarch images.

**Pull request closed without merging**
