### PR TITLE
Refactor metric extraction from MQTT

### PR DESCRIPTION
**Pull request by hikhvar**
This commit allows to extract the metric name from the topic path. Now
it can be configured if all metrics are in a object in a certain topic
or if every topic contains exactly one metric. However, currently these
modes can not be mixed.

This should solve #26 
TODO:
* [ ] Update documentation
* [x] Add unit tests

### CODE REVIEW

**Comment by dsienkiewicz** [comment]
I'm interested in metric per topic configuration for Shelly Plug S.
Could you merge this PR, as I can run this exporter only from Docker image ?

**Comment by hikhvar** [comment]
I will merge this and release release candidate.

**Comment by hikhvar** [comment]
This is part of: https://github.com/hikhvar/mqtt2prometheus/releases/tag/v0.1.5-RC1

**Comment by hikhvar** [comment]
@dsienkiewicz please test with  https://github.com/hikhvar/mqtt2prometheus/releases/tag/v0.1.5-RC2
I found a bug in the shelly implementation

**Pull request merged**
